"""Resolved-core classifier cases for Python/C parity."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from border_loop_classifier import LoopContext, ResolvedStep, classify_resolved_prefix

IboTopology = Literal["ONE_BIND", "ZERO_BIND"]


@dataclass
class ResolvedCorpusCase:
    name: str
    ctx: LoopContext
    steps: list[ResolvedStep]
    walk_exhausted: bool = True
    ibo_bind_topology: IboTopology = "ONE_BIND"
    expected_semantic: dict[str, Any] = field(default_factory=dict)
    expected_implementable: dict[str, Any] = field(default_factory=dict)

    def run_python(self) -> tuple[dict[str, Any], dict[str, Any]]:
        sem = classify_resolved_prefix(
            self.ctx,
            self.steps,
            ibo_bind_topology=self.ibo_bind_topology,
            max_scan_steps=None,
            walk_exhausted=self.walk_exhausted,
        )
        impl = classify_resolved_prefix(
            self.ctx,
            self.steps,
            ibo_bind_topology=self.ibo_bind_topology,
            max_scan_steps=128,
            walk_exhausted=self.walk_exhausted,
        )
        return _prefix_dict(sem), _prefix_dict(impl)


def _prefix_dict(result) -> dict[str, Any]:
    return {
        "run_length": result.run_length,
        "batch_eligible": result.batch_eligible,
        "elim": result.eligible_draw_calls_eliminable,
        "termination": result.termination_kind.name,
        "stop_reason_mask": int(result.stop_reason_mask),
        "boundary_reason_mask": int(result.boundary_reason_mask),
    }


def _ctx(**kwargs) -> LoopContext:
    defaults = {
        "mode": 0,
        "cached_color": 5,
        "cached_vbo_index": 1,
        "skip_or_visibility_mask": 0xFF,
        "outer_batch_index": 8,
        "bound_ibo_identity": 100,
        "ibo_known": True,
    }
    defaults.update(kwargs)
    return LoopContext(**defaults)


def _step(
    record_index: int,
    vis: int,
    color: int,
    *,
    valid: bool = True,
    tri: int = 4,
    vbo: int = 1,
    ibo_id: int = 100,
    ibo_arg: int = 100,
) -> ResolvedStep:
    return ResolvedStep(
        record_index,
        vis,
        color,
        valid,
        triangle_count=tri,
        vbo_table_index=vbo,
        ibo_identity=ibo_id,
        ibo_argument=ibo_arg,
    )


def build_resolved_corpus() -> list[ResolvedCorpusCase]:
    cases: list[ResolvedCorpusCase] = []

    cases.append(
        ResolvedCorpusCase(
            "invalid_resolved_valid",
            _ctx(cached_color=1),
            [_step(0, 0xFF, 1, valid=False)],
        )
    )

    cases.append(
        ResolvedCorpusCase(
            "invisible_skip_no_deref",
            _ctx(cached_color=1, skip_or_visibility_mask=0x0),
            [_step(0, 0x00, 1)],
        )
    )

    steps_ibo = [_step(i, 3, 5, ibo_id=0x0000000112345678, ibo_arg=0x0000000112345678) for i in range(3)]
    steps_ibo.append(_step(3, 3, 5, ibo_id=0x0000000212345678, ibo_arg=0x0000000212345678))
    cases.append(
        ResolvedCorpusCase(
            "high_bit_ibo_transition",
            _ctx(cached_color=5, cached_vbo_index=1),
            steps_ibo,
        )
    )

    cases.append(
        ResolvedCorpusCase(
            "color_and_vbo_boundary",
            _ctx(cached_color=5, cached_vbo_index=1),
            [_step(0, 3, 5), _step(1, 3, 5), _step(2, 3, 9, vbo=2)],
        )
    )

    cases.append(
        ResolvedCorpusCase(
            "zero_triangles_boundary",
            _ctx(),
            [_step(0, 3, 5), _step(1, 3, 5), _step(2, 3, 5), _step(3, 3, 5, tri=0)],
        )
    )

    long_steps = [_step(i, 3, 5) for i in range(200)]
    cases.append(
        ResolvedCorpusCase(
            "scan_cap_vs_walk",
            _ctx(),
            long_steps,
            walk_exhausted=False,
        )
    )

    cases.append(
        ResolvedCorpusCase(
            "zero_bind_mismatch",
            _ctx(bound_ibo_identity=50, ibo_known=True),
            [_step(0, 3, 5), _step(1, 3, 5)],
            ibo_bind_topology="ZERO_BIND",
        )
    )

    cases.append(
        ResolvedCorpusCase(
            "null_ibo_argument",
            _ctx(),
            [_step(0, 3, 5, ibo_id=100, ibo_arg=0)],
        )
    )

    for case in cases:
        if not case.expected_semantic:
            sem, impl = case.run_python()
            case.expected_semantic = sem
            case.expected_implementable = impl
    return cases


def write_c_resolved_fixture(path: Path) -> None:
    cases = build_resolved_corpus()
    lines: list[str] = [
        "/* Generated by border_loop_resolved_corpus.write_c_resolved_fixture */",
        "#ifndef BORDER_LOOP_RESOLVED_PARITY_CASES_H",
        "#define BORDER_LOOP_RESOLVED_PARITY_CASES_H",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "#include \"border_loop_classifier.h\"",
        "",
        "typedef struct {",
        "    const char *name;",
        "    eu4_border_loop_context_t ctx;",
        "    const eu4_border_resolved_step_t *steps;",
        "    uint32_t step_count;",
        "    eu4_border_ibo_topology_t ibo_topology;",
        "    bool walk_exhausted;",
        "} eu4_border_resolved_parity_case_t;",
        "",
    ]
    for i, case in enumerate(cases):
        lines.append(f"static const eu4_border_resolved_step_t case{i}_steps[] = {{")
        for s in case.steps:
            lines.append(
                "    {"
                f" .record_index = {s.record_index}, .visibility_byte = {s.visibility_byte}, "
                f".color_byte = {s.color_byte}, .resolved_valid = {'true' if s.resolved_valid else 'false'}, "
                f".triangle_count = {s.triangle_count}, .vbo_table_index = {s.vbo_table_index}, "
                f".ibo_identity = 0x{s.ibo_identity:x}ull, .ibo_argument = 0x{s.ibo_argument:x}ull }},"
            )
        lines.append("};")
        ctx = case.ctx
        topo = "EU4_BORDER_IBO_ZERO_BIND" if case.ibo_bind_topology == "ZERO_BIND" else "EU4_BORDER_IBO_ONE_BIND"
        lines.append(f"static const eu4_border_resolved_parity_case_t case{i}_meta = {{")
        lines.append(f'    "{case.name}",')
        lines.append(
            f"    {{ .mode = {ctx.mode}u, .cached_color = {ctx.cached_color}u, "
            f".cached_vbo_index = {ctx.cached_vbo_index}u, "
            f".skip_or_visibility_mask = {ctx.skip_or_visibility_mask}u, "
            f".outer_batch_index = {ctx.outer_batch_index & 0xFFFFFFFF}u, "
            f".bound_ibo_identity = {ctx.bound_ibo_identity}ull, "
            f".ibo_known = {'true' if ctx.ibo_known else 'false'}, "
            f".color_known = true, .vbo_known = true, "
            f".deferred_attrib_upload_pending = false, .secondary_upload_pending = false }},"
        )
        lines.append(f"    case{i}_steps, {len(case.steps)}u, {topo}, {'true' if case.walk_exhausted else 'false'} }};")

    lines.append("static const eu4_border_resolved_parity_case_t *const EU4_BORDER_RESOLVED_PARITY_CASES[] = {")
    for i in range(len(cases)):
        lines.append(f"    &case{i}_meta,")
    lines.append("};")
    lines.append(f"#define EU4_BORDER_RESOLVED_PARITY_CASE_COUNT {len(cases)}")
    lines.append("#endif")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
